#!/bin/bash

#Install docker
dpkg -s docker &> /dev/null
if [ $? -eq 0 ]; then
    echo "Package docker is installed!"
else
    sudo apt isntall docker
    sudo apt install docker-compose
fi

#Start service docker
sudo systemctl enable docker
sudo systemctl start docker

#start build production
docker build -t koompiplay .
docker-compose up -d